### ISSUE TITLE
Opening the project

### ISSUE THREAD

**Issue by mifrazmurthaja** [bradgermain/Facial-Recognition#1]
Hi @bgermain ! How to run this project? Which IDE you used to create this project. I'm very much interested in this project.

**Comment by bradgermain** [comment]
Hi @mifrazmurthaja! I believe you run the project from main.java. It's been quite a few years since I worked with this, but I think the IDE used was eclipse.

**Comment by mifrazmurthaja** [comment]
Thanks @bgermain
